TipCase:
  m: 8
  n: 12
  tool_index: 0
  bottom_right:
    down:
    - 61.54
    - 282.29
    - -76.0
    - 90.03
    up:
    - 61.54
    - 282.29
    - -15.21
    - 90.03
  bottom_left:
    down:
    - 60.54
    - 218.94
    - -76.0
    - 90.03
    up:
    - 60.54
    - 218.94
    - -15.21
    - 90.03
  top_left:
    down:
    - -36.56
    - 219.44
    - -76.0
    - 90.03
    up:
    - -36.56
    - 219.44
    - -15.21
    - 90.03
  top_right:
    down:
    - -37.06
    - 282.29
    - -76.21
    - 90.03
    up:
    - -37.06
    - 282.29
    - -15.21
    - 90.03
AssemblyPost:
  prepare_location:
  - 7.97
  - -352.17
  - 58.73
  - -90
  drop_location:
  - 7.97
  - -352.17
  - 22.91
  - -90
Liquid:
  m: 4
  n: 4
  tool_index: 0
  bottom_right:
    down:
    - 49.35
    - 398.79
    - -72.49
    - 90.03
    up:
    - 49.35
    - 398.79
    - -42.49
    - 90.03
  bottom_left:
    down:
    - 49.05
    - 328.28
    - -72.49
    - 90
    up:
    - 49.05
    - 328.28
    - -42.49
    - 90
  top_left:
    down:
    - -21.15
    - 328.28
    - -72.49
    - 90.03
    up:
    - -21.15
    - 328.28
    - -42.49
    - 90.03
  top_right:
    down:
    - -21.15
    - 399.29
    - -72.09
    - 90.03
    up:
    - -21.15
    - 399.29
    - -42.49
    - 90.03
Home:
- 90
- 0
- 0
- 0
