set(_AMENT_PACKAGE_NAME "battery_lab_custom_msg")
set(battery_lab_custom_msg_VERSION "0.0.0")
set(battery_lab_custom_msg_MAINTAINER "yuanjian <yuanjian@uchicago.edu>")
set(battery_lab_custom_msg_BUILD_DEPENDS "rosidl_default_generators" "sensor_msgs" "builtin_interfaces")
set(battery_lab_custom_msg_BUILDTOOL_DEPENDS "ament_cmake")
set(battery_lab_custom_msg_BUILD_EXPORT_DEPENDS "sensor_msgs" "builtin_interfaces")
set(battery_lab_custom_msg_BUILDTOOL_EXPORT_DEPENDS )
set(battery_lab_custom_msg_EXEC_DEPENDS "rosidl_default_runtime" "sensor_msgs" "builtin_interfaces")
set(battery_lab_custom_msg_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(battery_lab_custom_msg_GROUP_DEPENDS )
set(battery_lab_custom_msg_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(battery_lab_custom_msg_DEPRECATED "")
set(battery_lab_custom_msg_EXPORT_TAGS)
list(APPEND battery_lab_custom_msg_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
