set(_AMENT_PACKAGE_NAME "battery_lab_bringup")
set(battery_lab_bringup_VERSION "0.0.0")
set(battery_lab_bringup_MAINTAINER "yuanjian <yuanjian@uchicago.edu>")
set(battery_lab_bringup_BUILD_DEPENDS )
set(battery_lab_bringup_BUILDTOOL_DEPENDS "ament_cmake")
set(battery_lab_bringup_BUILD_EXPORT_DEPENDS )
set(battery_lab_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(battery_lab_bringup_EXEC_DEPENDS )
set(battery_lab_bringup_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(battery_lab_bringup_GROUP_DEPENDS )
set(battery_lab_bringup_MEMBER_OF_GROUPS )
set(battery_lab_bringup_DEPRECATED "")
set(battery_lab_bringup_EXPORT_TAGS)
list(APPEND battery_lab_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
